const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

export function createDashboard(root, content, attempts) {
  const chapters = new Map(content.concepts.chapters.map((item) => [item.id, item.name]));
  const state = { searchText: '', chapter: '', skill: '', difficulty: '', page: 1, pageSize: 20 };
  const options = (values, label, selected) => `<option value="">${label}</option>${values.map((value) => `<option value="${escapeHtml(value)}" ${String(value) === String(selected) ? 'selected' : ''}>${escapeHtml(value)}</option>`).join('')}`;
  const filteredQuestions = () => content.index.query(state);
  const render = (route) => {
    root.innerHTML = route === 'question-bank' ? questionBank() : route === 'architecture' ? architecture() : dashboard();
    bindRouteButtons();
    if (route === 'question-bank') bindQuestionBank();
  };
  const bindRouteButtons = () => root.querySelectorAll('[data-route]').forEach((button) => button.addEventListener('click', () => { location.hash = button.dataset.route; }));
  const dashboard = () => `<section class="hero"><div><p class="eyebrow">PHYSICS LEARNING APP V2</p><h1>Học đúng chỗ,<br>tiến bộ từng bước.</h1><p>Nền tảng local-first chuẩn bị cho hệ thống học vật lý thích ứng.</p><button class="primary" data-route="question-bank">Khám phá question bank →</button></div><div class="orbit" aria-hidden="true">∑</div></section><section class="metrics"><article><small>ĐIỂM TRUNG BÌNH</small><strong>—</strong><span>${attempts.length ? 'Chưa có bài chấm điểm' : 'Chưa có bài làm'}</span></article><article><small>ĐÃ HOÀN THÀNH</small><strong>${attempts.length}</strong><span>Bài làm</span></article><article><small>QUESTION BANK</small><strong>${content.catalog.questionCount}</strong><span>${content.catalog.verifiedQuestionCount} câu đã xác minh</span></article><article class="accent"><small>CONTENT VERSION</small><strong>${escapeHtml(content.version.contentVersion)}</strong><span>IndexedDB v${content.version.databaseVersion}</span></article></section><section class="columns"><article class="panel"><div class="panel-title"><div><p class="eyebrow">FOUNDATION</p><h2>Kiến trúc đã sẵn sàng</h2></div><b>Phase 1</b></div>${content.catalog.chapters.map((id) => `<div class="progress"><span>${escapeHtml(chapters.get(id) ?? id)}</span><strong>—</strong><i><em></em></i></div>`).join('')}</article><article class="panel"><div class="panel-title"><div><p class="eyebrow">LEARNING MODES</p><h2>Lộ trình học tập</h2></div></div><button class="mode" data-route="question-bank"><span>▤</span><div><b>Question bank</b><small>${content.catalog.questionCount} câu hỏi có metadata</small></div>→</button><div class="mode disabled"><span>◌</span><div><b>Adaptive practice</b><small>Sẽ mở ở Phase 3</small></div>○</div><div class="mode disabled"><span>↺</span><div><b>Wrong question review</b><small>Sẽ mở ở Phase 4</small></div>○</div></article></section>`;
  const questionBank = () => `<section class="heading"><div><p class="eyebrow">CONTENT EXPLORER</p><h1>Question bank</h1><p>${content.catalog.questionCount} câu hỏi có metadata phục vụ Adaptive Engine.</p></div><span class="pill">v${escapeHtml(content.version.contentVersion)}</span></section><div class="toolbar filters"><input data-search placeholder="Tìm theo câu hỏi, skill hoặc concept…" value="${escapeHtml(state.searchText)}"><select data-filter="chapter">${options(content.catalog.chapters, 'Tất cả chapter', state.chapter)}</select><select data-filter="skill">${options(content.catalog.skills, 'Tất cả skill', state.skill)}</select><select data-filter="difficulty">${options([1, 2, 3, 4, 5], 'Mọi độ khó', state.difficulty)}</select><span data-result-count></span></div><section class="question-grid" data-question-list></section><nav class="pagination" data-pagination aria-label="Question bank pagination"></nav>`;
  const questionCard = (question) => `<article class="question" data-question="${escapeHtml(question.id)}"><div class="question-meta"><span>${escapeHtml(chapters.get(question.chapter) ?? question.chapter)}</span><span>Độ khó ${question.difficulty}/5</span><b>${escapeHtml(question.sourceType)}</b></div><h2>${escapeHtml(question.question)}</h2><div class="tags"><span>${escapeHtml(question.concept)}</span><span>${escapeHtml(question.skill)}</span></div><details><summary>Xem metadata học tập</summary><dl><dt>Common errors</dt><dd>${escapeHtml(question.commonErrors.join(', '))}</dd><dt>Prerequisites</dt><dd>${escapeHtml(question.prerequisites.join(', '))}</dd><dt>Relations</dt><dd>${question.variantOf ? `variantOf: ${escapeHtml(question.variantOf)}` : '—'}</dd></dl></article>`;
  const updateQuestionList = () => {
    const questions = filteredQuestions(), pageCount = Math.max(1, Math.ceil(questions.length / state.pageSize));
    state.page = Math.min(state.page, pageCount);
    const start = (state.page - 1) * state.pageSize;
    root.querySelector('[data-question-list]').innerHTML = questions.slice(start, start + state.pageSize).map(questionCard).join('') || '<p class="empty-state">Không tìm thấy câu hỏi phù hợp.</p>';
    root.querySelector('[data-result-count]').textContent = `${questions.length}/${content.catalog.questionCount} câu`;
    root.querySelector('[data-pagination]').innerHTML = `<button data-page="prev" ${state.page === 1 ? 'disabled' : ''}>← Trước</button><span>Trang ${state.page}/${pageCount}</span><button data-page="next" ${state.page === pageCount ? 'disabled' : ''}>Sau →</button>`;
    root.querySelectorAll('[data-page]').forEach((button) => button.addEventListener('click', () => { state.page += button.dataset.page === 'next' ? 1 : -1; updateQuestionList(); }));
  };
  const bindQuestionBank = () => {
    root.querySelector('[data-search]').addEventListener('input', (event) => { state.searchText = event.target.value; state.page = 1; updateQuestionList(); });
    root.querySelectorAll('[data-filter]').forEach((select) => select.addEventListener('change', (event) => { state[event.target.dataset.filter] = event.target.value; state.page = 1; updateQuestionList(); }));
    updateQuestionList();
  };
  const architecture = () => `<section class="heading"><div><p class="eyebrow">SYSTEM FOUNDATION</p><h1>Kiến trúc V2</h1><p>Question index, IndexedDB và persistence layer cho các agent tiếp theo.</p></div></section><section class="columns"><article class="panel"><p class="eyebrow">CONTENT INDEX</p><h2>${content.catalog.questionCount} câu đã lập chỉ mục</h2><div class="store-list"><code>● byId</code><code>● byChapter / byTopic</code><code>● byConcept / bySkill</code><code>● byDifficulty / byTag</code><code>● token search index</code></div></article><article class="panel"><p class="eyebrow">INDEXEDDB</p><h2>Stores được bảo toàn khi update</h2><div class="store-list">${['students', 'attempts', 'answers', 'mastery', 'errors', 'reviewQueue', 'settings', 'questionProgress'].map((store) => `<code>● ${store}</code>`).join('')}</div></article></section>`;
  return { render };
}
