const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

export function createDashboard(root, content, attempts) {
  const chapters = new Map(content.concepts.chapters.map((item) => [item.id, item.name]));
  const render = (route) => {
    root.innerHTML = route === 'question-bank' ? questionBank() : route === 'architecture' ? architecture() : dashboard();
    root.querySelectorAll('[data-route]').forEach((button) => button.addEventListener('click', () => { location.hash = button.dataset.route; }));
    root.querySelector('[data-search]')?.addEventListener('input', (event) => {
      const query = event.target.value.toLowerCase();
      root.querySelectorAll('[data-question]').forEach((card) => { card.hidden = query && !card.dataset.question.includes(query); });
    });
  };
  const dashboard = () => `<section class="hero"><div><p class="eyebrow">PHYSICS LEARNING APP V2</p><h1>Học đúng chỗ,<br>tiến bộ từng bước.</h1><p>Nền tảng local-first chuẩn bị cho hệ thống học vật lý thích ứng.</p><button class="primary" data-route="question-bank">Khám phá question bank →</button></div><div class="orbit" aria-hidden="true">∑</div></section><section class="metrics"><article><small>ĐIỂM TRUNG BÌNH</small><strong>${attempts.length ? '—' : '—'}</strong><span>Chưa có bài làm</span></article><article><small>ĐÃ HOÀN THÀNH</small><strong>${attempts.length}</strong><span>Bài làm</span></article><article><small>QUESTION BANK</small><strong>${content.questions.length}</strong><span>câu đã validate</span></article><article class="accent"><small>CONTENT VERSION</small><strong>${escapeHtml(content.version.contentVersion)}</strong><span>IndexedDB v${content.version.databaseVersion}</span></article></section><section class="columns"><article class="panel"><div class="panel-title"><div><p class="eyebrow">FOUNDATION</p><h2>Kiến trúc đã sẵn sàng</h2></div><b>Phase 1</b></div>${content.catalog.chapters.map((id) => `<div class="progress"><span>${escapeHtml(chapters.get(id) ?? id)}</span><strong>—</strong><i><em></em></i></div>`).join('')}</article><article class="panel"><div class="panel-title"><div><p class="eyebrow">LEARNING MODES</p><h2>Lộ trình học tập</h2></div></div><button class="mode" data-route="question-bank"><span>▤</span><div><b>Question bank</b><small>Khám phá câu hỏi theo chương</small></div>→</button><div class="mode disabled"><span>◌</span><div><b>Adaptive practice</b><small>Sẽ mở ở Phase 3</small></div>○</div><div class="mode disabled"><span>↺</span><div><b>Wrong question review</b><small>Sẽ mở ở Phase 4</small></div>○</div></article></section>`;
  const questionBank = () => `<section class="heading"><div><p class="eyebrow">CONTENT EXPLORER</p><h1>Question bank</h1><p>${content.questions.length} câu hỏi có metadata phục vụ Adaptive Engine.</p></div><span class="pill">v${escapeHtml(content.version.contentVersion)}</span></section><div class="toolbar"><input data-search placeholder="Tìm theo câu hỏi, skill hoặc concept…"><span>${content.questions.length} câu đã xác thực</span></div><section class="question-grid">${content.questions.map((question) => `<article class="question" data-question="${escapeHtml([question.id, question.question, question.skill, question.concept].join(' ').toLowerCase())}"><div class="question-meta"><span>${escapeHtml(chapters.get(question.chapter) ?? question.chapter)}</span><span>Độ khó ${question.difficulty}/5</span><b>${escapeHtml(question.sourceType)}</b></div><h2>${escapeHtml(question.question)}</h2><div class="tags"><span>${escapeHtml(question.concept)}</span><span>${escapeHtml(question.skill)}</span></div><details><summary>Xem metadata học tập</summary><dl><dt>Common errors</dt><dd>${escapeHtml(question.commonErrors.join(', '))}</dd><dt>Prerequisites</dt><dd>${escapeHtml(question.prerequisites.join(', '))}</dd><dt>Relations</dt><dd>${question.variantOf ? `variantOf: ${escapeHtml(question.variantOf)}` : '—'}</dd></dl></details></article>`).join('')}</section>`;
  const architecture = () => `<section class="heading"><div><p class="eyebrow">SYSTEM FOUNDATION</p><h1>Kiến trúc V2</h1><p>Shared contracts và persistence layer cho các agent tiếp theo.</p></div></section><section class="columns"><article class="panel"><p class="eyebrow">INDEXEDDB</p><h2>Stores được bảo toàn khi update</h2><div class="store-list">${['students', 'attempts', 'answers', 'mastery', 'errors', 'reviewQueue', 'settings', 'questionProgress'].map((store) => `<code>● ${store}</code>`).join('')}</div></article><article class="panel"><p class="eyebrow">HANDOFF CONTRACTS</p><h2>Engine giao tiếp bằng schema chung</h2><p>Exam tạo Attempt. Mastery đọc Attempt và tạo MasteryProfile/ErrorProfile. Adaptive đọc QuestionBank, MasteryProfile, ErrorProfile và ReviewQueue.</p><p><a href="./architecture.md">Mở architecture.md</a> · <a href="./PROJECT_STATUS.md">Mở project status</a></p></article></section>`;
  return { render };
}

